services:
  prometheus:
    image: prom/prometheus:v2.33.3
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-data:/prometheus'
  nature-remo-exporter:
    env_file:
      - ./nature-remo-exporter/.env 
    build: ./nature-remo-exporter
    ports:
      - '8000:8000'
  grafana:
    image: grafana/grafana:8.3.6
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning'
      - './grafana/dashboards:/var/lib/grafana/dashboards'
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/nature-remo.json

volumes:
  prometheus-data:
  grafana-data:
